# CodeCademy Hurricanes Project

Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occurred.

In [1]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma', 'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September', 'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July', 'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], ['The Bahamas', 'Northeastern United States'], ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'], ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], ['The Caribbean', 'United States East coast'], ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'], ['Central America', 'Yucatn Peninsula', 'South Florida'], ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'], ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'], ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'], ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'], ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], ['Central America', 'United States Gulf Coast']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]

## Exercise 1

Begin by looking at the **damages** list. The list contains strings representing the total cost in USD($) caused by 34 category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded ("Damages not recorded"), while the rest are written in the format "Prefix-B/M", where B stands for billions (1000000000) and M stands for millions (1000000).

Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as "Damages not recorded".

Test your function with the data stored in damages.

In [2]:
conversion = {"M": 1000000,"B": 1000000000}

def convert_damages(damages):
    updated_damages = []
    for data in damages:
        if data[-1] == "M":
            new_value = float(data[:-1])*conversion["M"]
            updated_damages.append(new_value)
        elif data[-1] == "B":
            new_value = float(data[:-1])*conversion["B"]
            updated_damages.append(new_value)
        else:
            updated_damages.append(data)
    return updated_damages
    
updated_damages = convert_damages(damages)
print(updated_damages)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


## Exercise 2

Additional data collected on the 34 strongest Atlantic hurricanes are provided in a series of lists. The data includes:

- names: names of the hurricanes
- months: months in which the hurricanes occurred
- years: years in which the hurricanes occurred
- max_sustained_winds: maximum sustained winds (miles per hour) of the hurricanes
- areas_affected: list of different areas affected by each of the hurricanes
- deaths: total number of deaths caused by each of the hurricanes
The data is organized such that the data at each index, from 0 to 33, corresponds to the same hurricane.

For example, names[0] yields the “Cuba I” hurricane, which ouccred in months[0] (October) years[0] (1924).

Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (Name, Month, Year,Max Sustained Wind, Areas Affected, Damage, Death) about the hurricane.

Thus the key "Cuba I" would have the value:
> {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}.

Test your function on the lists of data provided.

In [3]:
def hurricanes_all_info(names, months, years, max_sustained_winds, areas_affected, updated_damages, deaths):
    hurricanes_data = {}
    for index in range(0,34):
        hurricanes_data[names[index]] = {"Name": names[index], "Month": months[index], "Year": years[index], 
                                     "Max Sustained Wind": max_sustained_winds[index], "Areas Affected": areas_affected[index],
                                    "Damage": updated_damages[index], "Deaths": deaths[index]}
    return hurricanes_data

hurricanes_data = hurricanes_all_info(names, months, years, max_sustained_winds, areas_affected, updated_damages, deaths)
#Check for the keys in the new dicrionary
#print(hurricanes_data.keys())
#Show the data for a specific hurricane
print(hurricanes_data["Cuba II"])

{'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}


## Exercise 3

In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key 1932 would yield the value:
> [{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}].

Test your function on your hurricane dictionary.

In [4]:
def year_hurricane_dict(hurricanes_data):
    hurricanes_year_info = {}
    for value in hurricanes_data.values():
        hurricane_year = value["Year"]
        hurricane_info = value
        if hurricane_year in hurricanes_year_info.keys():
            hurricanes_year_info[hurricane_year].append(hurricane_info)
        else:
            hurricanes_year_info[hurricane_year] = [hurricane_info]
    return hurricanes_year_info

hurricanes_year_info = year_hurricane_dict(hurricanes_data)
print(hurricanes_year_info[1932])

[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]


## Exercise 4
You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

Test your function on your hurricane dictionary.

In [5]:
def areas_affected_cout(areas_affected):
    areas_times_affected = {}

    for data in areas_affected:
        for areas in data:
            if areas not in areas_times_affected.keys():
                count = 1
                areas_times_affected[areas] = count
            else:
                count += 1
                areas_times_affected[areas] = count
    return areas_times_affected

areas_times_affected = areas_affected_cout(areas_affected)
print(areas_times_affected)

{'Central America': 2, 'Mexico': 3, 'Cuba': 2, 'Florida': 3, 'The Bahamas': 5, 'Lesser Antilles': 4, 'United States East Coast': 2, 'Atlantic Canada': 3, 'Northeastern United States': 2, 'Jamaica': 2, 'Cayman Islands': 1, 'Bermuda': 2, 'Texas': 4, 'Tamaulipas': 1, 'Yucatn Peninsula': 9, 'Georgia': 1, 'The Carolinas': 1, 'Virginia': 1, 'Southeastern United States': 1, 'Southwestern Quebec': 1, 'New England': 1, 'Louisiana': 1, 'Midwestern United States': 1, 'The Caribbean': 2, 'United States Gulf Coast': 3, 'United States East coast': 1, 'South Texas': 1, 'Venezuela': 2, 'Hispaniola': 1, 'South Florida': 1, 'Greater Antilles': 9, 'Bahamas': 5, 'Eastern United States': 1, 'Ontario': 1, 'Windward Islands': 1, 'Nicaragua': 1, 'Honduras': 1, 'Antilles': 1, 'Colombia': 1, 'Cape Verde': 1, 'British Virgin Islands': 1, 'U.S. Virgin Islands': 1, 'Virgin Islands': 1, 'Puerto Rico': 1, 'Dominican Republic': 1, 'Turks and Caicos Islands': 1}


## Exercise 5 
Write a function that finds the area affected by the most hurricanes, and how often it was hit.

Test your function on your affected area dictionary.

In [6]:
def most_affected_area(areas_times_affected):
    count = 0
    area = ""
    for key,value in areas_times_affected.items():
        if count < value:
            count = value
            area = key
    return "The most affected areas was " + area + " being hitted " + str(count) + " times!"

most_affected_area = most_affected_area(areas_times_affected)
print(most_affected_area)

The most affected areas was Yucatn Peninsula being hitted 9 times!


## Exercise 6
Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

Test your function on your hurricane dictionary.

In [7]:
def most_deadly_hurricane(hurricanes_data):
    #Create dictionary with hurricane name and associated deaths
    hurricane_deaths = {}
    for values in hurricanes_data.values():
        hurricanes = values["Name"]
        deaths = values["Deaths"]
        hurricane_deaths[hurricanes] = deaths
        #Find the most deadly hurricane 
        count = 0
        name = ""
        for key, value in hurricane_deaths.items():
            if count < value:
                name = key
                count = value
    return "The hurricane that caused the greatest number of deaths was " + name + ", killing about " + str(count) + " people!"

most_deadly_hurricane = most_deadly_hurricane(hurricanes_data)
print(most_deadly_hurricane)

The hurricane that caused the greatest number of deaths was Mitch, killing about 19325 people!


## Exercise 7
Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

mortality_scale = {0: 0,
                   1: 100,
                   2: 500,
                   3: 1000,
                   4: 10000}
                   
For example, a hurricane with a 1 mortality rating would have resulted in greater than 0 but less than or equal to 100 deaths. A hurricane with a 5 mortality rating would have resulted in greater than 10000 deaths.

Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

Test your function on your hurricane dictionary.

In [8]:
def mortality_rating(hurricanes_data):
    mortality_rating = {0: [], 1: [], 2: [], 3:[], 4:[]}
    for values in hurricanes_data.values():
        hurricanes = values["Name"]
        mortality = values["Deaths"]
        if mortality == 0:
            mortality_rating[0].append(hurricanes)
        elif mortality > 0 and mortality <= 100:
            mortality_rating[1].append(hurricanes)
        elif mortality > 100 and mortality <= 500:
            mortality_rating[2].append(hurricanes)
        elif mortality > 500 and mortality <= 1000:
            mortality_rating[3].append(hurricanes)
        else:
            mortality_rating[4].append(hurricanes)
    return mortality_rating

mortality_rating = mortality_rating(hurricanes_data)
print(mortality_rating)

{0: [], 1: ['Cuba I', 'Bahamas', 'Carol', 'Carla', 'Edith', 'Anita', 'Andrew', 'Isabel', 'Emily', 'Wilma', 'Dean', 'Michael'], 2: ['CubaBrownsville', 'Tampico', 'Labor Day', 'Hattie', 'Camille', 'Allen', 'Gilbert', 'Hugo', 'Ivan', 'Rita', 'Felix', 'Irma'], 3: ['New England', 'Beulah', 'Matthew'], 4: ['San Felipe II Okeechobee', 'Cuba II', 'Janet', 'David', 'Mitch', 'Katrina', 'Maria']}


## Exercise 8
Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

Test your function on your hurricane dictionary.

In [9]:
def most_costly_hurricane(hurricanes_data):
    hurricane_damage = {}
    cost = 0
    name = ""
    for hurricanes in hurricanes_data:
        damage = hurricanes_data[hurricanes]["Damage"]
        if damage == "Damages not recorded":
            continue
        elif damage > cost:
            cost = damage
            name = hurricanes
    return "The most destructive hurricane was " + name + " causing a damage costing " + str(cost) + " USD($)!"

most_costly_hurricane = most_costly_hurricane(hurricanes_data)
print(most_costly_hurricane)

The most destructive hurricane was Katrina causing a damage costing 125000000000.0 USD($)!


## Exercise 9
Lastly, you want to rate hurricanes according to how much damage they cause.

Write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.

damage_scale = {0: 0,
                1: 100000000,
                2: 1000000000,
                3: 10000000000,
                4: 50000000000}

For example, a hurricane with a 1 damage rating would have resulted in damages greater than 0 USD but less than or equal to 100000000 USD. A hurricane with a 5 damage rating would have resulted in damages greater than 50000000000 USD (talk about a lot of money).

Store the hurricanes in a new dictionary where the keys are damage ratings and the values are lists containing a dictionary for each hurricane that falls into that damage rating.

Test your function on your hurricane dictionary.

In [10]:
def hurricane_damage_rating(hurricanes_data):
    damage_rating = {0: [], 1:[], 2:[], 3:[], 4:[]}
    for values in hurricanes_data.values():
            hurricanes = values["Name"]
            damage = values["Damage"]
            if damage == "Damages not recorded":
                continue
            elif damage == 0:
                damage_rating[0].append(hurricanes)
            elif damage > 0 and damage <= 100000000:
                damage_rating[1].append(hurricanes)
            elif damage > 100000000 and damage <= 1000000000:
                damage_rating[2].append(hurricanes)
            elif damage > 1000000000 and damage <= 10000000000:
                damage_rating[3].append(hurricanes)
            else:
                damage_rating[4].append(hurricanes)
    return damage_rating

hurricane_damage_rating = hurricane_damage_rating(hurricanes_data)
print(hurricane_damage_rating)

{0: [], 1: ['San Felipe II Okeechobee', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Carol', 'Janet', 'Hattie', 'Edith'], 2: ['New England', 'Carla', 'Beulah', 'Felix'], 3: ['Camille', 'David', 'Allen', 'Gilbert', 'Hugo', 'Mitch', 'Isabel', 'Emily', 'Dean'], 4: ['Andrew', 'Ivan', 'Katrina', 'Rita', 'Wilma', 'Matthew', 'Irma', 'Maria', 'Michael']}
